-- =====================================================================
-- Portfólio — schema de demonstração
-- Três domínios isolados em schemas próprios: compras, faturamento, legal.
-- Todos os dados são sintéticos (ver supabase/seed).
-- =====================================================================

create schema if not exists compras;
create schema if not exists faturamento;
create schema if not exists legal;

comment on schema compras is 'Demo: ciclo de compras (solicitação → pedido → nota fiscal). Dados fictícios.';
comment on schema faturamento is 'Demo: análise de faturamento. Dados fictícios.';
comment on schema legal is 'Demo: BI jurídico. Dados fictícios.';

-- ---------------------------------------------------------------------
-- COMPRAS
-- ---------------------------------------------------------------------
create table compras.centros_custo (
  id          bigint generated by default as identity primary key,
  codigo      text not null unique,
  nome        text not null,
  created_at  timestamptz not null default now()
);

create table compras.usuarios (
  id          bigint generated by default as identity primary key,
  nome        text not null,
  perfil      text not null check (perfil in ('Solicitante', 'Comprador')),
  created_at  timestamptz not null default now()
);

create table compras.fornecedores (
  id            bigint generated by default as identity primary key,
  razao_social  text not null unique,
  categoria     text not null,
  uf            char(2) not null,
  created_at    timestamptz not null default now()
);

create table compras.produtos (
  id                bigint generated by default as identity primary key,
  codigo            text not null unique,
  descricao         text not null,
  unidade           text not null,
  categoria         text not null,
  preco_referencia  numeric(14,2) not null check (preco_referencia > 0),
  created_at        timestamptz not null default now()
);

create table compras.solicitacoes (
  id                bigint generated by default as identity primary key,
  numero            text not null unique,
  data_solicitacao  date not null,
  solicitante_id    bigint not null references compras.usuarios(id),
  centro_custo_id   bigint not null references compras.centros_custo(id),
  prioridade        text not null check (prioridade in ('Normal', 'Alta', 'Urgente')),
  status            text not null check (status in ('Em aprovação', 'Aprovada', 'Reprovada', 'Cancelada', 'Em pedido', 'Atendida')),
  data_aprovacao    date,
  justificativa     text,
  created_at        timestamptz not null default now(),
  constraint ck_sc_aprovacao check (data_aprovacao is null or data_aprovacao >= data_solicitacao)
);

create table compras.solicitacao_itens (
  id              bigint generated by default as identity primary key,
  solicitacao_id  bigint not null references compras.solicitacoes(id) on delete cascade,
  produto_id      bigint not null references compras.produtos(id),
  quantidade      numeric(14,3) not null check (quantidade > 0),
  valor_estimado  numeric(14,2) not null check (valor_estimado >= 0),
  created_at      timestamptz not null default now()
);

create table compras.pedidos (
  id                     bigint generated by default as identity primary key,
  numero                 text not null unique,
  solicitacao_id         bigint not null unique references compras.solicitacoes(id),
  fornecedor_id          bigint not null references compras.fornecedores(id),
  comprador_id           bigint not null references compras.usuarios(id),
  data_emissao           date not null,
  data_prevista_entrega  date not null,
  status                 text not null check (status in ('Aguardando entrega', 'Parcialmente recebido', 'Recebido', 'Cancelado')),
  created_at             timestamptz not null default now(),
  constraint ck_pc_prevista check (data_prevista_entrega >= data_emissao)
);

create table compras.pedido_itens (
  id              bigint generated by default as identity primary key,
  pedido_id       bigint not null references compras.pedidos(id) on delete cascade,
  produto_id      bigint not null references compras.produtos(id),
  quantidade      numeric(14,3) not null check (quantidade > 0),
  valor_unitario  numeric(14,2) not null check (valor_unitario >= 0),
  created_at      timestamptz not null default now()
);

create table compras.notas_fiscais (
  id                bigint generated by default as identity primary key,
  numero            text not null,
  serie             text not null,
  pedido_id         bigint not null references compras.pedidos(id),
  fornecedor_id     bigint not null references compras.fornecedores(id),
  data_emissao      date not null,
  data_recebimento  date not null,
  valor_total       numeric(14,2) not null check (valor_total >= 0),
  created_at        timestamptz not null default now(),
  constraint uq_nf unique (fornecedor_id, serie, numero),
  constraint ck_nf_datas check (data_recebimento >= data_emissao)
);

create index ix_sc_data on compras.solicitacoes (data_solicitacao);
create index ix_sc_status on compras.solicitacoes (status);
create index ix_sc_cc on compras.solicitacoes (centro_custo_id);
create index ix_sci_sc on compras.solicitacao_itens (solicitacao_id);
create index ix_pc_fornecedor on compras.pedidos (fornecedor_id);
create index ix_pc_data on compras.pedidos (data_emissao);
create index ix_pci_pc on compras.pedido_itens (pedido_id);
create index ix_nf_pc on compras.notas_fiscais (pedido_id);

-- ---------------------------------------------------------------------
-- FATURAMENTO
-- ---------------------------------------------------------------------
create table faturamento.regioes (
  id    bigint generated by default as identity primary key,
  nome  text not null unique
);

create table faturamento.vendedores (
  id         bigint generated by default as identity primary key,
  nome       text not null,
  regiao_id  bigint not null references faturamento.regioes(id),
  created_at timestamptz not null default now()
);

create table faturamento.clientes (
  id           bigint generated by default as identity primary key,
  nome         text not null unique,
  segmento     text not null,
  uf           char(2) not null,
  regiao_id    bigint not null references faturamento.regioes(id),
  vendedor_id  bigint not null references faturamento.vendedores(id),
  created_at   timestamptz not null default now()
);

create table faturamento.categorias (
  id    bigint generated by default as identity primary key,
  nome  text not null unique
);

create table faturamento.produtos (
  id            bigint generated by default as identity primary key,
  codigo        text not null unique,
  descricao     text not null,
  categoria_id  bigint not null references faturamento.categorias(id),
  preco_base    numeric(14,2) not null check (preco_base > 0),
  created_at    timestamptz not null default now()
);

create table faturamento.notas (
  id                  bigint generated by default as identity primary key,
  numero              text not null,
  serie               text not null,
  data_emissao        date not null,
  cliente_id          bigint not null references faturamento.clientes(id),
  vendedor_id         bigint not null references faturamento.vendedores(id),
  tipo_operacao       text not null check (tipo_operacao in ('Venda', 'Devolução')),
  status              text not null check (status in ('Autorizada', 'Cancelada')),
  nota_referencia_id  bigint references faturamento.notas(id),
  created_at          timestamptz not null default now(),
  constraint uq_nota unique (serie, numero),
  constraint ck_devolucao_ref check (tipo_operacao <> 'Devolução' or nota_referencia_id is not null)
);

create table faturamento.nota_itens (
  id              bigint generated by default as identity primary key,
  nota_id         bigint not null references faturamento.notas(id) on delete cascade,
  produto_id      bigint not null references faturamento.produtos(id),
  quantidade      numeric(14,3) not null check (quantidade > 0),
  valor_unitario  numeric(14,2) not null check (valor_unitario >= 0),
  desconto        numeric(5,4) not null default 0 check (desconto between 0 and 1),
  valor_total     numeric(14,2) not null check (valor_total >= 0),
  created_at      timestamptz not null default now()
);

create index ix_nota_data on faturamento.notas (data_emissao);
create index ix_nota_cliente on faturamento.notas (cliente_id);
create index ix_nota_vendedor on faturamento.notas (vendedor_id);
create index ix_nota_ref on faturamento.notas (nota_referencia_id);
create index ix_item_nota on faturamento.nota_itens (nota_id);
create index ix_item_produto on faturamento.nota_itens (produto_id);

-- ---------------------------------------------------------------------
-- LEGAL
-- ---------------------------------------------------------------------
create table legal.clientes (
  id        bigint generated by default as identity primary key,
  nome      text not null unique,
  segmento  text not null,
  created_at timestamptz not null default now()
);

create table legal.areas (
  id    bigint generated by default as identity primary key,
  nome  text not null unique
);

create table legal.advogados (
  id       bigint generated by default as identity primary key,
  nome     text not null,
  area_id  bigint not null references legal.areas(id),
  created_at timestamptz not null default now()
);

create table legal.tribunais (
  id      bigint generated by default as identity primary key,
  sigla   text not null unique,
  nome    text not null,
  esfera  text not null check (esfera in ('Estadual', 'Trabalhista', 'Federal')),
  uf      char(2) not null
);

create table legal.processos (
  id                 bigint generated by default as identity primary key,
  numero             text not null unique,
  cliente_id         bigint not null references legal.clientes(id),
  advogado_id        bigint not null references legal.advogados(id),
  area_id            bigint not null references legal.areas(id),
  tribunal_id        bigint not null references legal.tribunais(id),
  polo               text not null check (polo in ('Ativo', 'Passivo')),
  fase               text not null,
  status             text not null check (status in ('Em andamento', 'Aguardando audiência', 'Aguardando julgamento', 'Em recurso', 'Em execução', 'Suspenso', 'Encerrado')),
  risco              text not null check (risco in ('Provável', 'Possível', 'Remota')),
  objeto             text not null,
  data_distribuicao  date not null,
  data_encerramento  date,
  resultado          text check (resultado in ('Favorável', 'Parcialmente favorável', 'Acordo', 'Desfavorável')),
  valor_causa        numeric(16,2) not null check (valor_causa >= 0),
  valor_provisao     numeric(16,2) not null default 0 check (valor_provisao >= 0),
  created_at         timestamptz not null default now(),
  constraint ck_encerramento check (
    (status = 'Encerrado' and data_encerramento is not null and resultado is not null)
    or (status <> 'Encerrado' and data_encerramento is null)
  ),
  constraint ck_datas check (data_encerramento is null or data_encerramento >= data_distribuicao)
);

create table legal.movimentacoes (
  id           bigint generated by default as identity primary key,
  processo_id  bigint not null references legal.processos(id) on delete cascade,
  data         date not null,
  tipo         text not null,
  descricao    text not null,
  created_at   timestamptz not null default now()
);

create table legal.prazos (
  id              bigint generated by default as identity primary key,
  processo_id     bigint not null references legal.processos(id) on delete cascade,
  tipo            text not null,
  data_limite     date not null,
  status          text not null check (status in ('Pendente', 'Cumprido')),
  responsavel_id  bigint not null references legal.advogados(id),
  created_at      timestamptz not null default now()
);

create index ix_proc_status on legal.processos (status);
create index ix_proc_area on legal.processos (area_id);
create index ix_proc_tribunal on legal.processos (tribunal_id);
create index ix_proc_dist on legal.processos (data_distribuicao);
create index ix_mov_proc_data on legal.movimentacoes (processo_id, data);
create index ix_prazo_pendente on legal.prazos (data_limite) where status = 'Pendente';
create index ix_prazo_proc on legal.prazos (processo_id);

-- ---------------------------------------------------------------------
-- SEGURANÇA: somente leitura para os papéis públicos do Supabase.
-- RLS ativo em todas as tabelas; nenhuma política de escrita é criada.
-- ---------------------------------------------------------------------
do $$
declare r record;
begin
  for r in
    select schemaname, tablename from pg_tables
    where schemaname in ('compras', 'faturamento', 'legal')
  loop
    execute format('alter table %I.%I enable row level security', r.schemaname, r.tablename);
    execute format(
      'create policy "leitura publica (demo)" on %I.%I for select to anon, authenticated using (true)',
      r.schemaname, r.tablename
    );
  end loop;
end $$;
